In [76]:
import numpy as np

In [77]:
#soru1
np.array([10,15,30,45,60])

array([10, 15, 30, 45, 60])

In [78]:
#soru2
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
#soru3
np.arange(50,101,5)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100])

In [80]:
#soru4
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
#soru5
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
#soru6
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [83]:
#soru7
np.random.randint(10,30,5)

array([16, 19, 27, 22, 18])

In [84]:
#soru8
np.random.randn(10)

array([-1.40341087, -0.59935859,  0.53545853, -1.9508632 ,  0.0439043 ,
        1.98926956, -0.23412795, -1.71097563, -1.47804665,  1.51717264])

In [85]:
#soru9
s9=np.random.randint(-50,50,(3,5))
s9

array([[-36,  38, -23,  44, -10],
       [-33, -22, -22, -10,  10],
       [ 17,  14,  33, -11,   7]])

In [86]:
#soru10
toplam=0
for i in range(3):
    for j in range(5):
        toplam=np.add(toplam,s9[i][j])
toplam

-4

In [87]:
#soru11
max=s9.max()
min=s9.min()
mean=s9.mean()
print("max=",max," min=",min," mean=",mean)

max= 44  min= -36  mean= -0.26666666666666666


In [88]:
#soru12
s9.argmax()

3

In [89]:
#soru13
s13=np.arange(10,21)

s13[:3]

array([10, 11, 12])

In [90]:
#soru14
s13[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [91]:
#soru15
s9[0,:5]

array([-36,  38, -23,  44, -10])

In [92]:
#soru16
s9[1,2]

-22

In [93]:
#soru17
s9[0:,0]

array([-36, -33,  17])

In [94]:
#soru18
np.square(s9)

array([[1296, 1444,  529, 1936,  100],
       [1089,  484,  484,  100,  100],
       [ 289,  196, 1089,  121,   49]], dtype=int32)

In [112]:
#soru19
a=s9[s9%2==0]
a[a>0]

array([38, 44, 10, 14])